package com.navarromugas.views;

import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import javax.swing.AbstractAction;
import javax.swing.event.ChangeListener;

/**
 @author Martin
 */
public class VentanaJuegoDeLaVida extends javax.swing.JFrame {

	/**
	 Creates new form JuegoDeLaVida
	 */
	public VentanaJuegoDeLaVida() {
		initComponents();
	}

	/**
	 This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    barraDeHerramientas = new javax.swing.JToolBar();
    correrSimulacion = new javax.swing.JButton();
    pausarSimulacion = new javax.swing.JButton();
    avanzarUnaGeneracion = new javax.swing.JButton();
    velocidadDeSimulacion = new javax.swing.JSlider();
    revivirCelulasAlAzar = new javax.swing.JButton();
    matarTodasLasCelulas = new javax.swing.JButton();
    cargarMundo = new javax.swing.JButton();
    guardarMundo = new javax.swing.JButton();
    barraDeEstado = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Juego de la vida (Conway's Game Of Life)");
    setPreferredSize(new java.awt.Dimension(490, 570));
    setResizable(false);

    barraDeHerramientas.setRollover(true);

    correrSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/play.png"))); // NOI18N
    correrSimulacion.setToolTipText("Correr simulación");
    correrSimulacion.setFocusable(false);
    correrSimulacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    correrSimulacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(correrSimulacion);

    pausarSimulacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/pause.png"))); // NOI18N
    pausarSimulacion.setToolTipText("Pausar simulación");
    pausarSimulacion.setFocusable(false);
    pausarSimulacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    pausarSimulacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(pausarSimulacion);

    avanzarUnaGeneracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/next.png"))); // NOI18N
    avanzarUnaGeneracion.setToolTipText("Avanzar una generación");
    avanzarUnaGeneracion.setFocusable(false);
    avanzarUnaGeneracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    avanzarUnaGeneracion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(avanzarUnaGeneracion);

    velocidadDeSimulacion.setToolTipText("Velocidad de simulación");
    barraDeHerramientas.add(velocidadDeSimulacion);

    revivirCelulasAlAzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/grid.png"))); // NOI18N
    revivirCelulasAlAzar.setToolTipText("Dar vida al azar");
    revivirCelulasAlAzar.setFocusable(false);
    revivirCelulasAlAzar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    revivirCelulasAlAzar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(revivirCelulasAlAzar);

    matarTodasLasCelulas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/cross.png"))); // NOI18N
    matarTodasLasCelulas.setToolTipText("Matar celulas vivas");
    matarTodasLasCelulas.setFocusable(false);
    matarTodasLasCelulas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    matarTodasLasCelulas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(matarTodasLasCelulas);

    cargarMundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/folder-2.png"))); // NOI18N
    cargarMundo.setToolTipText("Cargar mundo");
    cargarMundo.setFocusable(false);
    cargarMundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    cargarMundo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(cargarMundo);

    guardarMundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/navarromugas/resources/floppy.png"))); // NOI18N
    guardarMundo.setToolTipText("Guardar mundo");
    guardarMundo.setFocusable(false);
    guardarMundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    guardarMundo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    barraDeHerramientas.add(guardarMundo);

    getContentPane().add(barraDeHerramientas, java.awt.BorderLayout.NORTH);

    barraDeEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    barraDeEstado.setPreferredSize(new java.awt.Dimension(100, 16));
    barraDeEstado.setLayout(new javax.swing.BoxLayout(barraDeEstado, javax.swing.BoxLayout.LINE_AXIS));
    barraDeEstado.add(jLabel1);

    getContentPane().add(barraDeEstado, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton avanzarUnaGeneracion;
  private javax.swing.JPanel barraDeEstado;
  private javax.swing.JToolBar barraDeHerramientas;
  private javax.swing.JButton cargarMundo;
  private javax.swing.JButton correrSimulacion;
  private javax.swing.JButton guardarMundo;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JButton matarTodasLasCelulas;
  private javax.swing.JButton pausarSimulacion;
  private javax.swing.JButton revivirCelulasAlAzar;
  private javax.swing.JSlider velocidadDeSimulacion;
  // End of variables declaration//GEN-END:variables

	private javax.swing.JPanel simulacionDelMundo;

	public void mostrar() {
		setVisible(true);
	}

	public void agregarSimulador(javax.swing.JPanel grilla) {
		simulacionDelMundo = grilla;
		getContentPane().add(simulacionDelMundo, java.awt.BorderLayout.CENTER);
		pack();
	}

	public void agregarAccionCorrerSimulacion(AbstractAction action) {
		correrSimulacion.addActionListener(action);
	}

	public void agregarAccionPausarSimulacion(AbstractAction action) {
		pausarSimulacion.addActionListener(action);
	}

	public void agregarAccionAvanzarUnaGeneracion(AbstractAction action) {
		avanzarUnaGeneracion.addActionListener(action);
	}

	public void agregarObservadorDeCambiosVelocidadDeSimulacion(ChangeListener listener) {
		velocidadDeSimulacion.addChangeListener(listener);
	}

	public void agregarAccionRevivirCelulasAlAzar(AbstractAction action) {
		revivirCelulasAlAzar.addActionListener(action);
	}

	public void agregarAccionMatarTodasLasCelulas(AbstractAction action) {
		matarTodasLasCelulas.addActionListener(action);
	}

	public void agregarAccionCargarMundo(AbstractAction action) {
		cargarMundo.addActionListener(action);
	}

	public void agregarAccionGuardarMundo(AbstractAction action) {
		guardarMundo.addActionListener(action);
	}

	public void agregarPanelSimuladorMouseListeners(MouseListener mouseListener, MouseMotionListener mouseMotionListener) {
		simulacionDelMundo.addMouseListener(mouseListener);
		simulacionDelMundo.addMouseMotionListener(mouseMotionListener);
	}
}
